# Generated by Django 3.2.6 on 2021-08-13 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='stream_platform',
            new_name='stream_platforms',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='movie',
            new_name='movies',
        ),
    ]
